import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
      </head>
      <body className={inter.className}>
        <div className="min-h-screen bg-gray-100 max-w-5xl mx-auto">
          <nav>
            <Link href="/">
              Home
            </Link>
            <Link href="/create">
              Create
            </Link>
            <Link href="/login">
              Login
            </Link>
          </nav>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
